package fr.eseo.servicesweb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-13T08:23:36.162+01:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "GestionHotelMethodesService",
                  wsdlLocation = "http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodesPort?wsdl",
                  targetNamespace = "http://servicesweb.eseo.fr/")
public class GestionHotelMethodesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicesweb.eseo.fr/", "GestionHotelMethodesService");
    public final static QName GestionHotelMethodesPort = new QName("http://servicesweb.eseo.fr/", "GestionHotelMethodesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodesPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionHotelMethodesService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodesPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionHotelMethodesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionHotelMethodesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionHotelMethodesService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GestionHotelMethodesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GestionHotelMethodesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GestionHotelMethodesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SEIGestionHotelMethodes
     */
    @WebEndpoint(name = "GestionHotelMethodesPort")
    public SEIGestionHotelMethodes getGestionHotelMethodesPort() {
        return super.getPort(GestionHotelMethodesPort, SEIGestionHotelMethodes.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SEIGestionHotelMethodes
     */
    @WebEndpoint(name = "GestionHotelMethodesPort")
    public SEIGestionHotelMethodes getGestionHotelMethodesPort(WebServiceFeature... features) {
        return super.getPort(GestionHotelMethodesPort, SEIGestionHotelMethodes.class, features);
    }

}
