
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.servicesweb;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-13T08:23:36.111+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "GestionHotelMethodesService",
                      portName = "GestionHotelMethodesPort",
                      targetNamespace = "http://servicesweb.eseo.fr/",
                      wsdlLocation = "http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodesPort?wsdl",
                      endpointInterface = "fr.eseo.servicesweb.SEIGestionHotelMethodes")

public class GestionHotelMethodesPortImpl implements SEIGestionHotelMethodes {

    private static final Logger LOG = Logger.getLogger(GestionHotelMethodesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.servicesweb.SEIGestionHotelMethodes#reserverChambre(fr.eseo.servicesweb.Reservation arg0)*
     */
    public int reserverChambre(fr.eseo.servicesweb.Reservation arg0) {
        LOG.info("Executing operation reserverChambre");
        System.out.println(arg0);
        try {
            int _return = 1307200508;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.servicesweb.SEIGestionHotelMethodes#trouverChambre(fr.eseo.servicesweb.Chambre arg0, int arg1, int arg2, java.lang.String arg3, java.lang.String arg4)*
     */
    public java.util.List<fr.eseo.servicesweb.Chambre> trouverChambre(fr.eseo.servicesweb.Chambre arg0, int arg1, int arg2, java.lang.String arg3, java.lang.String arg4) {
        LOG.info("Executing operation trouverChambre");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.util.List<fr.eseo.servicesweb.Chambre> _return = new java.util.ArrayList<fr.eseo.servicesweb.Chambre>();
            fr.eseo.servicesweb.Chambre _returnVal1 = new fr.eseo.servicesweb.Chambre();
            _returnVal1.setIdChambre(-1862606111);
            _returnVal1.setNbPlaceLit(1761564916);
            _returnVal1.setPrixJournalier(0.5804741f);
            _returnVal1.setTypeChambre("TypeChambre866242465");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.servicesweb.SEIGestionHotelMethodes#annulerChambre(int arg0)*
     */
    public boolean annulerChambre(int arg0) {
        LOG.info("Executing operation annulerChambre");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.servicesweb.SEIGestionHotelMethodes#payerChambre(int arg0)*
     */
    public boolean payerChambre(int arg0) {
        LOG.info("Executing operation payerChambre");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
