package fr.eseo.servicesweb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-13T08:23:36.140+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://servicesweb.eseo.fr/", name = "SEIGestionHotelMethodes")
@XmlSeeAlso({ObjectFactory.class})
public interface SEIGestionHotelMethodes {

    @WebMethod
    @RequestWrapper(localName = "reserverChambre", targetNamespace = "http://servicesweb.eseo.fr/", className = "fr.eseo.servicesweb.ReserverChambre")
    @ResponseWrapper(localName = "reserverChambreResponse", targetNamespace = "http://servicesweb.eseo.fr/", className = "fr.eseo.servicesweb.ReserverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.servicesweb.Reservation arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverChambre", targetNamespace = "http://servicesweb.eseo.fr/", className = "fr.eseo.servicesweb.TrouverChambre")
    @ResponseWrapper(localName = "trouverChambreResponse", targetNamespace = "http://servicesweb.eseo.fr/", className = "fr.eseo.servicesweb.TrouverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.servicesweb.Chambre> trouverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.servicesweb.Chambre arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "annulerChambre", targetNamespace = "http://servicesweb.eseo.fr/", className = "fr.eseo.servicesweb.AnnulerChambre")
    @ResponseWrapper(localName = "annulerChambreResponse", targetNamespace = "http://servicesweb.eseo.fr/", className = "fr.eseo.servicesweb.AnnulerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "payerChambre", targetNamespace = "http://servicesweb.eseo.fr/", className = "fr.eseo.servicesweb.PayerChambre")
    @ResponseWrapper(localName = "payerChambreResponse", targetNamespace = "http://servicesweb.eseo.fr/", className = "fr.eseo.servicesweb.PayerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean payerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
