
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.ee.serviceweb;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-19T09:55:48.788+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "GestionHotelMethodesService",
                      portName = "GestionHotelMethodesPort",
                      targetNamespace = "http://serviceweb.ee.eseo.fr/",
                      wsdlLocation = "http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodesPort?wsdl",
                      endpointInterface = "fr.eseo.ee.serviceweb.SEIGestionHotelMethodesJEE")

public class GestionHotelMethodesPortImpl implements SEIGestionHotelMethodesJEE {

    private static final Logger LOG = Logger.getLogger(GestionHotelMethodesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.ee.serviceweb.SEIGestionHotelMethodesJEE#annulerChambre(int arg0)*
     */
    public boolean annulerChambre(int arg0) {
        LOG.info("Executing operation annulerChambre");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.ee.serviceweb.SEIGestionHotelMethodesJEE#connexion(java.lang.String arg0, java.lang.String arg1)*
     */
    public int connexion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation connexion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = 435358728;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.ee.serviceweb.SEIGestionHotelMethodesJEE#payerChambre(int arg0)*
     */
    public boolean payerChambre(int arg0) {
        LOG.info("Executing operation payerChambre");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.ee.serviceweb.SEIGestionHotelMethodesJEE#reserverChambre(fr.eseo.ee.serviceweb.Reservation arg0)*
     */
    public int reserverChambre(fr.eseo.ee.serviceweb.Reservation arg0) {
        LOG.info("Executing operation reserverChambre");
        System.out.println(arg0);
        try {
            int _return = 1279619259;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.ee.serviceweb.SEIGestionHotelMethodesJEE#trouverChambre(fr.eseo.ee.serviceweb.Chambre arg0, int arg1, int arg2, java.lang.String arg3, java.lang.String arg4)*
     */
    public java.util.List<fr.eseo.ee.serviceweb.Chambre> trouverChambre(fr.eseo.ee.serviceweb.Chambre arg0, int arg1, int arg2, java.lang.String arg3, java.lang.String arg4) {
        LOG.info("Executing operation trouverChambre");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.util.List<fr.eseo.ee.serviceweb.Chambre> _return = new java.util.ArrayList<fr.eseo.ee.serviceweb.Chambre>();
            fr.eseo.ee.serviceweb.Chambre _returnVal1 = new fr.eseo.ee.serviceweb.Chambre();
            _returnVal1.setIdChambre(-2115596059);
            _returnVal1.setNbPlaceLit(2085513327);
            _returnVal1.setPrixJournalier(0.9872112f);
            _returnVal1.setTypeChambre("TypeChambre-661771790");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
