package fr.eseo.ee.serviceweb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-19T09:55:48.811+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://serviceweb.ee.eseo.fr/", name = "SEIGestionHotelMethodesJEE")
@XmlSeeAlso({ObjectFactory.class})
public interface SEIGestionHotelMethodesJEE {

    @WebMethod
    @RequestWrapper(localName = "annulerChambre", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.AnnulerChambre")
    @ResponseWrapper(localName = "annulerChambreResponse", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.AnnulerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "connexion", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.Connexion")
    @ResponseWrapper(localName = "connexionResponse", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.ConnexionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int connexion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "payerChambre", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.PayerChambre")
    @ResponseWrapper(localName = "payerChambreResponse", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.PayerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean payerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "reserverChambre", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.ReserverChambre")
    @ResponseWrapper(localName = "reserverChambreResponse", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.ReserverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.ee.serviceweb.Reservation arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverChambre", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.TrouverChambre")
    @ResponseWrapper(localName = "trouverChambreResponse", targetNamespace = "http://serviceweb.ee.eseo.fr/", className = "fr.eseo.ee.serviceweb.TrouverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.ee.serviceweb.Chambre> trouverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.ee.serviceweb.Chambre arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );
}
