
package fr.eseo.ee.serviceweb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-19T09:55:48.694+01:00
 * Generated source version: 3.3.0
 *
 */
public final class SEIGestionHotelMethodesJEE_GestionHotelMethodesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://serviceweb.ee.eseo.fr/", "GestionHotelMethodesService");

    private SEIGestionHotelMethodesJEE_GestionHotelMethodesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GestionHotelMethodesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GestionHotelMethodesService ss = new GestionHotelMethodesService(wsdlURL, SERVICE_NAME);
        SEIGestionHotelMethodesJEE port = ss.getGestionHotelMethodesPort();

        {
        System.out.println("Invoking annulerChambre...");
        int _annulerChambre_arg0 = 1627417889;
        boolean _annulerChambre__return = port.annulerChambre(_annulerChambre_arg0);
        System.out.println("annulerChambre.result=" + _annulerChambre__return);


        }
        {
        System.out.println("Invoking connexion...");
        java.lang.String _connexion_arg0 = "_connexion_arg0-392845903";
        java.lang.String _connexion_arg1 = "_connexion_arg1-573817962";
        int _connexion__return = port.connexion(_connexion_arg0, _connexion_arg1);
        System.out.println("connexion.result=" + _connexion__return);


        }
        {
        System.out.println("Invoking payerChambre...");
        int _payerChambre_arg0 = -2123669974;
        boolean _payerChambre__return = port.payerChambre(_payerChambre_arg0);
        System.out.println("payerChambre.result=" + _payerChambre__return);


        }
        {
        System.out.println("Invoking reserverChambre...");
        fr.eseo.ee.serviceweb.Reservation _reserverChambre_arg0 = new fr.eseo.ee.serviceweb.Reservation();
        _reserverChambre_arg0.setDateDeb(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-19T09:55:48.770+01:00"));
        _reserverChambre_arg0.setDateDebString("DateDebString-284355780");
        _reserverChambre_arg0.setDateFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2019-03-19T09:55:48.776+01:00"));
        _reserverChambre_arg0.setDateFinString("DateFinString-453087215");
        _reserverChambre_arg0.setIdChambre(1255421018);
        _reserverChambre_arg0.setIdClient(-802006044);
        _reserverChambre_arg0.setIdReservation(1534637419);
        _reserverChambre_arg0.setNbPlaces(1495394362);
        _reserverChambre_arg0.setPaiementEffectue(true);
        int _reserverChambre__return = port.reserverChambre(_reserverChambre_arg0);
        System.out.println("reserverChambre.result=" + _reserverChambre__return);


        }
        {
        System.out.println("Invoking trouverChambre...");
        fr.eseo.ee.serviceweb.Chambre _trouverChambre_arg0 = new fr.eseo.ee.serviceweb.Chambre();
        _trouverChambre_arg0.setIdChambre(-1934351760);
        _trouverChambre_arg0.setNbPlaceLit(-1426970332);
        _trouverChambre_arg0.setPrixJournalier(0.8678651f);
        _trouverChambre_arg0.setTypeChambre("TypeChambre733950060");
        int _trouverChambre_arg1 = -521063029;
        int _trouverChambre_arg2 = -1669191410;
        java.lang.String _trouverChambre_arg3 = "_trouverChambre_arg386562236";
        java.lang.String _trouverChambre_arg4 = "_trouverChambre_arg41248354233";
        java.util.List<fr.eseo.ee.serviceweb.Chambre> _trouverChambre__return = port.trouverChambre(_trouverChambre_arg0, _trouverChambre_arg1, _trouverChambre_arg2, _trouverChambre_arg3, _trouverChambre_arg4);
        System.out.println("trouverChambre.result=" + _trouverChambre__return);


        }

        System.exit(0);
    }

}
