
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.serviceswebbis;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-14T15:25:15.282+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "GestionHotelMethodesBisService",
                      portName = "GestionHotelMethodesBisPort",
                      targetNamespace = "http://serviceswebbis.eseo.fr/",
                      wsdlLocation = "http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodesBisPort?wsdl",
                      endpointInterface = "fr.eseo.serviceswebbis.SEIGestionHotelMethodeBis")

public class GestionHotelMethodesBisPortImpl implements SEIGestionHotelMethodeBis {

    private static final Logger LOG = Logger.getLogger(GestionHotelMethodesBisPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.serviceswebbis.SEIGestionHotelMethodeBis#payerChambre(int arg0)*
     */
    public boolean payerChambre(int arg0) {
        LOG.info("Executing operation payerChambre");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.serviceswebbis.SEIGestionHotelMethodeBis#annulerChambre(int arg0)*
     */
    public boolean annulerChambre(int arg0) {
        LOG.info("Executing operation annulerChambre");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.serviceswebbis.SEIGestionHotelMethodeBis#connexion(java.lang.String arg0, java.lang.String arg1)*
     */
    public int connexion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation connexion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -372793908;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.serviceswebbis.SEIGestionHotelMethodeBis#reserverChambre(fr.eseo.serviceswebbis.Reservation arg0)*
     */
    public int reserverChambre(fr.eseo.serviceswebbis.Reservation arg0) {
        LOG.info("Executing operation reserverChambre");
        System.out.println(arg0);
        try {
            int _return = -745571513;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.serviceswebbis.SEIGestionHotelMethodeBis#trouverChambre(fr.eseo.serviceswebbis.Chambre arg0, int arg1, int arg2, java.lang.String arg3, java.lang.String arg4)*
     */
    public java.util.List<fr.eseo.serviceswebbis.Chambre> trouverChambre(fr.eseo.serviceswebbis.Chambre arg0, int arg1, int arg2, java.lang.String arg3, java.lang.String arg4) {
        LOG.info("Executing operation trouverChambre");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.util.List<fr.eseo.serviceswebbis.Chambre> _return = new java.util.ArrayList<fr.eseo.serviceswebbis.Chambre>();
            fr.eseo.serviceswebbis.Chambre _returnVal1 = new fr.eseo.serviceswebbis.Chambre();
            _returnVal1.setIdChambre(-988983148);
            _returnVal1.setNbPlaceLit(-65209831);
            _returnVal1.setPrixJournalier(0.2956307f);
            _returnVal1.setTypeChambre("TypeChambre-359624146");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
