package fr.eseo.serviceswebbis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-14T15:25:15.314+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://serviceswebbis.eseo.fr/", name = "SEIGestionHotelMethodeBis")
@XmlSeeAlso({ObjectFactory.class})
public interface SEIGestionHotelMethodeBis {

    @WebMethod
    @RequestWrapper(localName = "payerChambre", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.PayerChambre")
    @ResponseWrapper(localName = "payerChambreResponse", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.PayerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean payerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "annulerChambre", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.AnnulerChambre")
    @ResponseWrapper(localName = "annulerChambreResponse", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.AnnulerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "connexion", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.Connexion")
    @ResponseWrapper(localName = "connexionResponse", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.ConnexionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int connexion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "reserverChambre", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.ReserverChambre")
    @ResponseWrapper(localName = "reserverChambreResponse", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.ReserverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.serviceswebbis.Reservation arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverChambre", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.TrouverChambre")
    @ResponseWrapper(localName = "trouverChambreResponse", targetNamespace = "http://serviceswebbis.eseo.fr/", className = "fr.eseo.serviceswebbis.TrouverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.serviceswebbis.Chambre> trouverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.serviceswebbis.Chambre arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );
}
