
package fr.eseo.serviceswebbis;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-14T15:25:15.202+01:00
 * Generated source version: 3.3.0
 *
 */
public final class SEIGestionHotelMethodeBis_GestionHotelMethodesBisPort_Client {

    private static final QName SERVICE_NAME = new QName("http://serviceswebbis.eseo.fr/", "GestionHotelMethodesBisService");

    private SEIGestionHotelMethodeBis_GestionHotelMethodesBisPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GestionHotelMethodesBisService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GestionHotelMethodesBisService ss = new GestionHotelMethodesBisService(wsdlURL, SERVICE_NAME);
        SEIGestionHotelMethodeBis port = ss.getGestionHotelMethodesBisPort();

        {
        System.out.println("Invoking payerChambre...");
        int _payerChambre_arg0 = -951516070;
        boolean _payerChambre__return = port.payerChambre(_payerChambre_arg0);
        System.out.println("payerChambre.result=" + _payerChambre__return);


        }
        {
        System.out.println("Invoking annulerChambre...");
        int _annulerChambre_arg0 = 497390208;
        boolean _annulerChambre__return = port.annulerChambre(_annulerChambre_arg0);
        System.out.println("annulerChambre.result=" + _annulerChambre__return);


        }
        {
        System.out.println("Invoking connexion...");
        java.lang.String _connexion_arg0 = "_connexion_arg01125867324";
        java.lang.String _connexion_arg1 = "_connexion_arg152424279";
        int _connexion__return = port.connexion(_connexion_arg0, _connexion_arg1);
        System.out.println("connexion.result=" + _connexion__return);


        }
        {
        System.out.println("Invoking reserverChambre...");
        fr.eseo.serviceswebbis.Reservation _reserverChambre_arg0 = new fr.eseo.serviceswebbis.Reservation();
        fr.eseo.serviceswebbis.Date _reserverChambre_arg0DateDeb = new fr.eseo.serviceswebbis.Date();
        _reserverChambre_arg0.setDateDeb(_reserverChambre_arg0DateDeb);
        fr.eseo.serviceswebbis.Date _reserverChambre_arg0DateFin = new fr.eseo.serviceswebbis.Date();
        _reserverChambre_arg0.setDateFin(_reserverChambre_arg0DateFin);
        _reserverChambre_arg0.setIdChambre(-639703213);
        _reserverChambre_arg0.setIdClient(400082941);
        _reserverChambre_arg0.setIdReservation(-1793154805);
        _reserverChambre_arg0.setNbPlaces(1821794820);
        _reserverChambre_arg0.setPaiementEffectue(true);
        int _reserverChambre__return = port.reserverChambre(_reserverChambre_arg0);
        System.out.println("reserverChambre.result=" + _reserverChambre__return);


        }
        {
        System.out.println("Invoking trouverChambre...");
        fr.eseo.serviceswebbis.Chambre _trouverChambre_arg0 = new fr.eseo.serviceswebbis.Chambre();
        _trouverChambre_arg0.setIdChambre(2096980510);
        _trouverChambre_arg0.setNbPlaceLit(-196378830);
        _trouverChambre_arg0.setPrixJournalier(0.80505323f);
        _trouverChambre_arg0.setTypeChambre("TypeChambre-216100835");
        int _trouverChambre_arg1 = 379418619;
        int _trouverChambre_arg2 = 1215502981;
        java.lang.String _trouverChambre_arg3 = "_trouverChambre_arg32053021410";
        java.lang.String _trouverChambre_arg4 = "_trouverChambre_arg4677976389";
        java.util.List<fr.eseo.serviceswebbis.Chambre> _trouverChambre__return = port.trouverChambre(_trouverChambre_arg0, _trouverChambre_arg1, _trouverChambre_arg2, _trouverChambre_arg3, _trouverChambre_arg4);
        System.out.println("trouverChambre.result=" + _trouverChambre__return);


        }

        System.exit(0);
    }

}
