package fr.eseo.ee.servicesweb3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-19T17:41:41.343+01:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "GestionHotelMethodes3Service",
                  wsdlLocation = "http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodes3Port?wsdl",
                  targetNamespace = "http://servicesweb3.ee.eseo.fr/")
public class GestionHotelMethodes3Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicesweb3.ee.eseo.fr/", "GestionHotelMethodes3Service");
    public final static QName GestionHotelMethodes3Port = new QName("http://servicesweb3.ee.eseo.fr/", "GestionHotelMethodes3Port");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodes3Port?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionHotelMethodes3Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ProjetGestionHotelSW/services/GestionHotelMethodes3Port?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionHotelMethodes3Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionHotelMethodes3Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionHotelMethodes3Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GestionHotelMethodes3Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GestionHotelMethodes3Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GestionHotelMethodes3Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SEIGestionHotelMethodes3
     */
    @WebEndpoint(name = "GestionHotelMethodes3Port")
    public SEIGestionHotelMethodes3 getGestionHotelMethodes3Port() {
        return super.getPort(GestionHotelMethodes3Port, SEIGestionHotelMethodes3.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SEIGestionHotelMethodes3
     */
    @WebEndpoint(name = "GestionHotelMethodes3Port")
    public SEIGestionHotelMethodes3 getGestionHotelMethodes3Port(WebServiceFeature... features) {
        return super.getPort(GestionHotelMethodes3Port, SEIGestionHotelMethodes3.class, features);
    }

}
