package fr.eseo.ee.servicesweb3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-19T17:41:41.335+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://servicesweb3.ee.eseo.fr/", name = "SEIGestionHotelMethodes3")
@XmlSeeAlso({ObjectFactory.class})
public interface SEIGestionHotelMethodes3 {

    @WebMethod
    @RequestWrapper(localName = "reserverChambre", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.ReserverChambre")
    @ResponseWrapper(localName = "reserverChambreResponse", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.ReserverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.ee.servicesweb3.Reservation arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverChambre", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.TrouverChambre")
    @ResponseWrapper(localName = "trouverChambreResponse", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.TrouverChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.ee.servicesweb3.Chambre> trouverChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.ee.servicesweb3.Chambre arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebMethod
    @RequestWrapper(localName = "payerChambre", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.PayerChambre")
    @ResponseWrapper(localName = "payerChambreResponse", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.PayerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean payerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "annulerChambre", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.AnnulerChambre")
    @ResponseWrapper(localName = "annulerChambreResponse", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.AnnulerChambreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "connexion", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.Connexion")
    @ResponseWrapper(localName = "connexionResponse", targetNamespace = "http://servicesweb3.ee.eseo.fr/", className = "fr.eseo.ee.servicesweb3.ConnexionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int connexion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
