
package fr.eseo.servicesweb.test;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-12T10:21:07.796+01:00
 * Generated source version: 3.3.0
 *
 */
public final class SEITrouverChambreSW_TrouverChambreSWPort_Client {

    private static final QName SERVICE_NAME = new QName("http://test.servicesweb.eseo.fr/", "TrouverChambreSWService");

    private SEITrouverChambreSW_TrouverChambreSWPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TrouverChambreSWService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TrouverChambreSWService ss = new TrouverChambreSWService(wsdlURL, SERVICE_NAME);
        SEITrouverChambreSW port = ss.getTrouverChambreSWPort();

        {
        System.out.println("Invoking trouverChambre...");
        fr.eseo.servicesweb.test.Chambre _trouverChambre_arg0 = new fr.eseo.servicesweb.test.Chambre();
        _trouverChambre_arg0.setIdChambre(1153667652);
        _trouverChambre_arg0.setNbPlaceLit(1184186787);
        _trouverChambre_arg0.setPrixJournalier(0.16988164f);
        _trouverChambre_arg0.setTypeChambre("TypeChambre-633893982");
        int _trouverChambre_arg1 = 1334252517;
        int _trouverChambre_arg2 = -2132710209;
        java.lang.String _trouverChambre_arg3 = "_trouverChambre_arg31942739380";
        java.lang.String _trouverChambre_arg4 = "_trouverChambre_arg41725595669";
        java.util.List<fr.eseo.servicesweb.test.Chambre> _trouverChambre__return = port.trouverChambre(_trouverChambre_arg0, _trouverChambre_arg1, _trouverChambre_arg2, _trouverChambre_arg3, _trouverChambre_arg4);
        System.out.println("trouverChambre.result=" + _trouverChambre__return);


        }

        System.exit(0);
    }

}
