package fr.eseo.servicesweb.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-12T10:21:07.893+01:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "TrouverChambreSWService",
                  wsdlLocation = "http://localhost:8080/ProjetGestionHotelSW/services/TrouverChambreSWPort?wsdl",
                  targetNamespace = "http://test.servicesweb.eseo.fr/")
public class TrouverChambreSWService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://test.servicesweb.eseo.fr/", "TrouverChambreSWService");
    public final static QName TrouverChambreSWPort = new QName("http://test.servicesweb.eseo.fr/", "TrouverChambreSWPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ProjetGestionHotelSW/services/TrouverChambreSWPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TrouverChambreSWService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ProjetGestionHotelSW/services/TrouverChambreSWPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TrouverChambreSWService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TrouverChambreSWService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TrouverChambreSWService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TrouverChambreSWService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TrouverChambreSWService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TrouverChambreSWService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SEITrouverChambreSW
     */
    @WebEndpoint(name = "TrouverChambreSWPort")
    public SEITrouverChambreSW getTrouverChambreSWPort() {
        return super.getPort(TrouverChambreSWPort, SEITrouverChambreSW.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SEITrouverChambreSW
     */
    @WebEndpoint(name = "TrouverChambreSWPort")
    public SEITrouverChambreSW getTrouverChambreSWPort(WebServiceFeature... features) {
        return super.getPort(TrouverChambreSWPort, SEITrouverChambreSW.class, features);
    }

}
