
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.servicesweb.test;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-03-12T10:21:07.868+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "TrouverChambreSWService",
                      portName = "TrouverChambreSWPort",
                      targetNamespace = "http://test.servicesweb.eseo.fr/",
                      wsdlLocation = "http://localhost:8080/ProjetGestionHotelSW/services/TrouverChambreSWPort?wsdl",
                      endpointInterface = "fr.eseo.servicesweb.test.SEITrouverChambreSW")

public class TrouverChambreSWPortImpl implements SEITrouverChambreSW {

    private static final Logger LOG = Logger.getLogger(TrouverChambreSWPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.servicesweb.test.SEITrouverChambreSW#trouverChambre(fr.eseo.servicesweb.test.Chambre arg0, int arg1, int arg2, java.lang.String arg3, java.lang.String arg4)*
     */
    public java.util.List<fr.eseo.servicesweb.test.Chambre> trouverChambre(fr.eseo.servicesweb.test.Chambre arg0, int arg1, int arg2, java.lang.String arg3, java.lang.String arg4) {
        LOG.info("Executing operation trouverChambre");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
            java.util.List<fr.eseo.servicesweb.test.Chambre> _return = new java.util.ArrayList<fr.eseo.servicesweb.test.Chambre>();
            fr.eseo.servicesweb.test.Chambre _returnVal1 = new fr.eseo.servicesweb.test.Chambre();
            _returnVal1.setIdChambre(-1650505213);
            _returnVal1.setNbPlaceLit(-689080835);
            _returnVal1.setPrixJournalier(0.34591973f);
            _returnVal1.setTypeChambre("TypeChambre228493154");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
